/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example

import com.google.common.collect.ImmutableList

class App {
    String getGreeting() {
        'Hello World!'
    }

    static void main(String[] args) {
        println new App().greeting
        ImmutableList<String> list = ImmutableList.of('a', 'b', 'c')
        println list
    }
}